{% set name = "torchmetrics" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d0e4957af0ea76438d2779fe1a626d8cba6cda8607eadb54267598153e7ea63

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - typing_extensions
    - numpy >1.20.0
    - packaging >17.1
    - setuptools
    - python >={{ python_min }}
    - pytorch >=1.10.0
    - lightning-utilities >=0.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - torchmetrics

about:
  home: https://pypi.org/project/torchmetrics/
  license: Apache-2.0
  license_file: LICENSE
  summary: Collection of PyTorch native metrics for easy evaluating machine learning models
  description: |
    Torchmetrics is a metrics API created for easy metric development and usage in both PyTorch and
    [PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/stable/). It was originally a part of
    Pytorch Lightning, but got split off so users could take advantage of the large collection of metrics
    implemented without having to install Pytorch Lightning (even though we would love for you to try it out).
    We currently have around 25+ metrics implemented and we continuously is adding more metrics, both within
    already covered domains (classification, regression ect.) but also new domains (object detection ect.).
    We make sure that all our metrics are rigorously tested such that you can trust them.
  doc_url: https://torchmetrics.readthedocs.io/
  dev_url: https://github.com/PyTorchLightning/metrics

extra:
  recipe-maintainers:
    - Borda
    - williamFalcon
