{% set name = "torchmetrics" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b1e5acdcc9beb05bfe369d3d56cfa5b143f060ebfd6079d19ccc59ba46465b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pretty_errors ==1.2.25
    - numpy >1.20.0
    - packaging >17.1
    - setuptools
    - python >=3.8
    - pytorch >=1.10.0
    - lightning-utilities >=0.8.0

test:
  imports:
    - torchmetrics

about:
  home: https://pypi.org/project/torchmetrics/
  license: Apache-2.0
  license_file: LICENSE
  summary: Collection of PyTorch native metrics for easy evaluating machine learning models
  description: |
    Torchmetrics is a metrics API created for easy metric development and usage in both PyTorch and
    [PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/stable/). It was originally a part of
    Pytorch Lightning, but got split off so users could take advantage of the large collection of metrics
    implemented without having to install Pytorch Lightning (even though we would love for you to try it out).
    We currently have around 25+ metrics implemented and we continuously is adding more metrics, both within
    already covered domains (classification, regression ect.) but also new domains (object detection ect.).
    We make sure that all our metrics are rigorously tested such that you can trust them.
  doc_url: https://torchmetrics.readthedocs.io/
  dev_url: https://github.com/PyTorchLightning/metrics

extra:
  recipe-maintainers:
    - Borda
    - williamFalcon
